// import CotegoryPageHero from "../Components/CotegoryPageHero";
import { useParams } from "react-router";
import { ArrowRight } from "lucide-react";
import CotegoryCard from "../../Components/CotegoryCard";

const Kabab = () => {
  const { category } = useParams();

  // const setcategory = category.join(" ");
  const allDishes = {
    EgginGravy: [
      {
        id: 1,
        dishName: "Egg Quorma (2 Pcs)",
        price: 148,
        image: "/images/egg-quorma.png",
        description: "Rich creamy egg quorma.",
        type: "nonVeg",
      },
      {
        id: 2,
        dishName: "Egg Kassa (2 Pcs)",
        price: 127,
        image: "/images/egg-kassa.png",
        description: "Spicy Bengali egg curry.",
        type: "nonVeg",
      },
      {
        id: 3,
        dishName: "Egg Masala (2 Pcs)",
        price: 137,
        image: "/images/egg-masala.png",
        description: "Eggs cooked in masala.",
        type: "nonVeg",
      },
      {
        id: 4,
        dishName: "Egg Tarka",
        price: 148,
        image: "/images/egg-tarka.png",
        description: "Flavorful egg tarka curry.",
        type: "nonVeg",
      },
    ],

    Fish: [
      {
        id: 1,
        dishName: "Fish Tikka (4 Pcs)",
        price: 454,
        image: "/images/fish-tikka.png",
        description: "Fresh grilled fish tikka.",
        type: "nonVeg",
      },
      {
        id: 2,
        dishName: "Fish Achari Tikka (4 Pcs)",
        price: 454,
        image: "/images/fish-achari-tikka.png",
        description: "Tangy achari fish tikka.",
        type: "nonVeg",
      },
      {
        id: 3,
        dishName: "Fish Ajwain Tikka (4 Pcs)",
        price: 454,
        image: "/images/fish-ajwain-tikka.png",
        description: "Ajwain flavored fish tikka.",
        type: "nonVeg",
      },
      {
        id: 4,
        dishName: "Fish Amritsari Tikka (4 Pcs)",
        price: 454,
        image: "/images/fish-amritsari-tikka.png",
        description: "Crispy Amritsari fish tikka.",
        type: "nonVeg",
      },
      {
        id: 5,
        dishName: "Tandoori Prawn (6 Pcs)",
        price: 454,
        image: "/images/tandoori-prawn.png",
        description: "Smoky grilled tandoori prawns.",
        type: "nonVeg",
      },
      {
        id: 6,
        dishName: "Malai Prawn Tikka (6 Pcs)",
        price: 475,
        image: "/images/malai-prawn-tikka.png",
        description: "Creamy malai prawn tikka.",
        type: "nonVeg",
      },
      {
        id: 7,
        dishName: "Prawn Garlic Kebab (6 Pcs)",
        price: 454,
        image: "/images/prawn-garlic-kebab.png",
        description: "Garlic flavored prawn kebab.",
        type: "nonVeg",
      },
      {
        id: 8,
        dishName: "Tandoori Pomfret (1 Pc)",
        price: 327,
        image: "/images/tandoori-pomfret.png",
        description: "Whole roasted tandoori pomfret.",
        type: "nonVeg",
      },
    ],

    Kabab: [
      {
        id: 1,
        dishName: "Dawat-e-Hind Spl. Kebab (6 Pcs)",
        price: 332,
        image: "/images/dawat-e-hind-kebab.png",
        description: "House special smoky kebab.",
        type: "nonVeg",
      },
      {
        id: 2,
        dishName: "Chelo Kebab",
        price: 377,
        image: "/images/chelo-kebab.png",
        description: "Classic kebab with aromatic rice.",
        type: "nonVeg",
      },
      {
        id: 3,
        dishName: "Banjara Kebab",
        price: 330,
        image: "/images/banjara-kebab.png",
        description: "Spicy grilled chicken kebab.",
        type: "nonVeg",
      },
      {
        id: 4,
        dishName: "Murgh Lazeez Tikka (6 Pcs)",
        price: 324,
        image: "/images/murgh-lazeez-tikka.png",
        description: "Tender flavorful chicken tikka.",
        type: "nonVeg",
      },
      {
        id: 5,
        dishName: "Afghani Tandoori Kebab (F/H)",
        price: 417,
        image: "/images/afghani-tandoori-kebab.png",
        description: "Creamy smoky Afghani kebab.",
        type: "nonVeg",
      },
      {
        id: 6,
        dishName: "Tandoori Chicken (F/H)",
        price: 396,
        image: "/images/tandoori-chicken.png",
        description: "Authentic smoky tandoori chicken.",
        type: "nonVeg",
      },
      {
        id: 7,
        dishName: "Chicken Tangri Kebab (F/H)",
        price: 332,
        image: "/images/chicken-tangri-kebab.png",
        description: "Juicy grilled chicken legs.",
        type: "nonVeg",
      },
      {
        id: 8,
        dishName: "Wings Chatpata Kebab (10 Pcs)",
        price: 343,
        image: "/images/wings-chatpata-kebab.png",
        description: "Tangy spicy chicken wings.",
        type: "nonVeg",
      },
      {
        id: 9,
        dishName: "Chicken Tikka Kebab (6 Pcs)",
        price: 248,
        image: "/images/chicken-tikka-kebab.png",
        description: "Boneless grilled chicken tikka.",
        type: "nonVeg",
      },
      {
        id: 10,
        dishName: "Chicken Reshmi Kebab (6 Pcs)",
        price: 269,
        image: "/images/chicken-reshmi-kebab.png",
        description: "Creamy soft chicken kebab.",
        type: "nonVeg",
      },
      {
        id: 11,
        dishName: "Chicken Hariyali Kebab (6 Pcs)",
        price: 248,
        image: "/images/chicken-hariyali-kebab.png",
        description: "Mint coriander flavored kebab.",
        type: "nonVeg",
      },
      {
        id: 12,
        dishName: "Chicken Malai Kebab (6 Pcs)",
        price: 280,
        image: "/images/chicken-malai-kebab.png",
        description: "Rich creamy chicken kebab.",
        type: "nonVeg",
      },
      {
        id: 13,
        dishName: "Chicken Kali Mirch Kebab (6 Pcs)",
        price: 248,
        image: "/images/chicken-kali-mirch-kebab.png",
        description: "Black pepper grilled chicken.",
        type: "nonVeg",
      },
      {
        id: 14,
        dishName: "Chicken Cheese Kebab (6 Pcs)",
        price: 322,
        image: "/images/chicken-cheese-kebab.png",
        description: "Cheesy smoky chicken bites.",
        type: "nonVeg",
      },
      {
        id: 15,
        dishName: "Chicken Alishan Kebab (6 Pcs)",
        price: 290,
        image: "/images/chicken-alishan-kebab.png",
        description: "Royal style chicken kebab.",
        type: "nonVeg",
      },
      {
        id: 16,
        dishName: "Chicken Afghani Kebab (6 Pcs)",
        price: 280,
        image: "/images/chicken-afghani-kebab.png",
        description: "Creamy Afghani grilled chicken.",
        type: "nonVeg",
      },
      {
        id: 17,
        dishName: "Chicken Jafrani Kebab (6 Pcs)",
        price: 311,
        image: "/images/chicken-jafrani-kebab.png",
        description: "Saffron flavored chicken kebab.",
        type: "nonVeg",
      },
      {
        id: 18,
        dishName: "Chicken Lassuni Kebab (6 Pcs)",
        price: 258,
        image: "/images/chicken-lassuni-kebab.png",
        description: "Garlic flavored grilled chicken.",
        type: "nonVeg",
      },
      {
        id: 19,
        dishName: "Chicken Angara Kebab (6 Pcs)",
        price: 280,
        image: "/images/chicken-angara-kebab.png",
        description: "Fiery charcoal grilled chicken.",
        type: "nonVeg",
      },
      {
        id: 20,
        dishName: "Chicken Seekh Kebab (6 Pcs)",
        price: 248,
        image: "/images/chicken-seekh-kebab.png",
        description: "Juicy minced chicken seekh.",
        type: "nonVeg",
      },
      {
        id: 21,
        dishName: "Chicken Raunaki Seekh Kebab (6 Pcs)",
        price: 258,
        image: "/images/chicken-raunaki-seekh-kebab.png",
        description: "Flavorful spicy seekh kebab.",
        type: "nonVeg",
      },
      {
        id: 22,
        dishName: "Chicken Boti Kebab (6 Pcs)",
        price: 264,
        image: "/images/chicken-boti-kebab.png",
        description: "Tender smoky chicken pieces.",
        type: "nonVeg",
      },
    ],

    RotiNaan: [
      {
        id: 1,
        dishName: "Dawat-e-Hind Spl. Naan",
        price: 132,
        image: "/images/dawat-special-naan.png",
        description: "House special soft naan.",
        type: "veg",
      },
      {
        id: 2,
        dishName: "Plain Naan",
        price: 47,
        image: "/images/plain-naan.png",
        description: "Soft freshly baked naan.",
        type: "veg",
      },
      {
        id: 3,
        dishName: "Butter Naan",
        price: 69,
        image: "/images/butter-naan.png",
        description: "Buttery soft tandoori naan.",
        type: "veg",
      },
      {
        id: 4,
        dishName: "Garlic Naan",
        price: 79,
        image: "/images/garlic-naan.png",
        description: "Garlic flavored soft naan.",
        type: "veg",
      },
      {
        id: 5,
        dishName: "Cheese Garlic Naan",
        price: 100,
        image: "/images/cheese-garlic-naan.png",
        description: "Cheesy garlic stuffed naan.",
        type: "veg",
      },
      {
        id: 6,
        dishName: "Keema Naan",
        price: 132,
        image: "/images/keema-naan.png",
        description: "Stuffed spicy keema naan.",
        type: "nonVeg",
      },
      {
        id: 7,
        dishName: "Cheese Chilli Naan",
        price: 90,
        image: "/images/cheese-chilli-naan.png",
        description: "Cheesy spicy chilli naan.",
        type: "veg",
      },
      {
        id: 8,
        dishName: "Baby Butter Naan",
        price: 32,
        image: "/images/baby-butter-naan.png",
        description: "Mini buttery soft naan.",
        type: "veg",
      },
      {
        id: 9,
        dishName: "Pardewali Naan",
        price: 84,
        image: "/images/pardewali-naan.png",
        description: "Traditional layered naan.",
        type: "veg",
      },
      {
        id: 10,
        dishName: "Cheese Naan",
        price: 79,
        image: "/images/cheese-naan.png",
        description: "Stuffed cheesy soft naan.",
        type: "veg",
      },
      {
        id: 11,
        dishName: "Pudina Lachha Paratha",
        price: 75,
        image: "/images/pudina-lachha-paratha.png",
        description: "Mint flavored flaky paratha.",
        type: "veg",
      },
      {
        id: 12,
        dishName: "Tandoori Lachha Paratha",
        price: 58,
        image: "/images/tandoori-lachha-paratha.png",
        description: "Layered crispy tandoori paratha.",
        type: "veg",
      },
      {
        id: 13,
        dishName: "Missi Roti",
        price: 65,
        image: "/images/missi-roti.png",
        description: "Healthy gram flour roti.",
        type: "veg",
      },
      {
        id: 14,
        dishName: "Rumali Roti",
        price: 32,
        image: "/images/rumali-roti.png",
        description: "Thin soft hand tossed roti.",
        type: "veg",
      },
      {
        id: 15,
        dishName: "Tandoori Roti",
        price: 26,
        image: "/images/tandoori-roti.png",
        description: "Fresh clay oven roti.",
        type: "veg",
      },
      {
        id: 16,
        dishName: "Butter Tandoori Roti",
        price: 37,
        image: "/images/butter-tandoori-roti.png",
        description: "Buttery crispy tandoori roti.",
        type: "veg",
      },
      {
        id: 17,
        dishName: "Aata Roti",
        price: 26,
        image: "/images/aata-roti.png",
        description: "Soft whole wheat roti.",
        type: "veg",
      },
      {
        id: 18,
        dishName: "Plain Kulcha",
        price: 39,
        image: "/images/plain-kulcha.png",
        description: "Soft fluffy plain kulcha.",
        type: "veg",
      },
      {
        id: 19,
        dishName: "Masala Kulcha",
        price: 79,
        image: "/images/masala-kulcha.png",
        description: "Spiced stuffed soft kulcha.",
        type: "veg",
      },
    ],

    Vegetable: [
      {
        id: 1,
        dishName: "Paneer Tikka",
        price: 243,
        image: "/images/paneer-tikka.png",
        description: "Grilled paneer cubes.",
        type: "veg",
      },
      {
        id: 2,
        dishName: "Hariyali Paneer Tikka",
        price: 243,
        image: "/images/hariyali-paneer-tikka.png",
        description: "Mint flavored paneer tikka.",
        type: "veg",
      },
      {
        id: 3,
        dishName: "Malai Paneer Tikka",
        price: 253,
        image: "/images/malai-paneer-tikka.png",
        description: "Creamy paneer tikka.",
        type: "veg",
      },
      {
        id: 4,
        dishName: "Makhmali Paneer Tikka",
        price: 317,
        image: "/images/makhmali-paneer-tikka.png",
        description: "Soft creamy paneer tikka.",
        type: "veg",
      },
      {
        id: 5,
        dishName: "Paneer Seekh Kebab",
        price: 243,
        image: "/images/paneer-seekh-kebab.png",
        description: "Juicy paneer seekh kebab.",
        type: "veg",
      },
      {
        id: 6,
        dishName: "Veg. Seekh Kebab",
        price: 211,
        image: "/images/veg-seekh-kebab.png",
        description: "Mixed vegetable seekh.",
        type: "veg",
      },
      {
        id: 7,
        dishName: "Paneer Butter Masala",
        price: 200,
        image: "/images/paneer-butter-masala.png",
        description: "Creamy butter paneer.",
        type: "veg",
      },
      {
        id: 8,
        dishName: "Kadai Paneer",
        price: 200,
        image: "/images/kadai-paneer.png",
        description: "Spicy kadai paneer.",
        type: "veg",
      },
      {
        id: 9,
        dishName: "Shahi Paneer",
        price: 200,
        image: "/images/shahi-paneer.png",
        description: "Rich royal paneer curry.",
        type: "veg",
      },
      {
        id: 10,
        dishName: "Palak Paneer",
        price: 200,
        image: "/images/palak-paneer.png",
        description: "Spinach paneer curry.",
        type: "veg",
      },
      {
        id: 11,
        dishName: "Paneer Do-Piyaza",
        price: 200,
        image: "/images/paneer-do-piyaza.png",
        description: "Paneer with onions.",
        type: "veg",
      },
      {
        id: 12,
        dishName: "Methi Malai Paneer",
        price: 200,
        image: "/images/methi-malai-paneer.png",
        description: "Creamy methi paneer.",
        type: "veg",
      },
      {
        id: 13,
        dishName: "Paneer Tikka Masala",
        price: 295,
        image: "/images/paneer-tikka-masala.png",
        description: "Paneer tikka curry.",
        type: "veg",
      },
      {
        id: 14,
        dishName: "Mix Veg",
        price: 148,
        image: "/images/mix-veg.png",
        description: "Fresh mixed vegetables.",
        type: "veg",
      },
      {
        id: 15,
        dishName: "Kadai Veg",
        price: 169,
        image: "/images/kadai-veg.png",
        description: "Spicy mixed vegetables.",
        type: "veg",
      },
      {
        id: 16,
        dishName: "Veg. Jhalfrazi",
        price: 190,
        image: "/images/veg-jhalfrazi.png",
        description: "Spicy vegetable curry.",
        type: "veg",
      },
      {
        id: 17,
        dishName: "Malai Kofta (4 Pcs)",
        price: 222,
        image: "/images/malai-kofta.png",
        description: "Creamy kofta curry.",
        type: "veg",
      },
      {
        id: 18,
        dishName: "Tarka",
        price: 137,
        image: "/images/tarka-dal.png",
        description: "Traditional dal tarka.",
        type: "veg",
      },
      {
        id: 19,
        dishName: "Dal Fry",
        price: 116,
        image: "/images/dal-fry.png",
        description: "Classic yellow dal.",
        type: "veg",
      },
      {
        id: 20,
        dishName: "Chana Masala",
        price: 137,
        image: "/images/chana-masala.png",
        description: "Spicy chickpea curry.",
        type: "veg",
      },
      {
        id: 21,
        dishName: "Green Peas Masala",
        price: 148,
        image: "/images/green-peas-masala.png",
        description: "Green peas curry.",
        type: "veg",
      },
      {
        id: 22,
        dishName: "Mushroom Masala",
        price: 200,
        image: "/images/mushroom-masala.png",
        description: "Spicy mushroom curry.",
        type: "veg",
      },
      {
        id: 23,
        dishName: "Matar Mushroom",
        price: 200,
        image: "/images/matar-mushroom.png",
        description: "Peas and mushroom curry.",
        type: "veg",
      },
      {
        id: 24,
        dishName: "Dal Makhani",
        price: 158,
        image: "/images/dal-makhani.png",
        description: "Creamy black lentils.",
        type: "veg",
      },
    ],

    BiryaniRice: [
      {
        id: 1,
        dishName: "Dawat-e-Hind Spl. Biryani",
        price: 411,
        image: "/images/dawat-special-biryani.png",
        description: "Special mixed biryani platter.",
        type: "nonVeg",
      },
      {
        id: 2,
        dishName: "Mutton Biryani",
        price: 317,
        image: "/images/mutton-biryani.png",
        description: "Classic mutton biryani.",
        type: "nonVeg",
      },
      {
        id: 3,
        dishName: "Mutton Awadhi Biryani",
        price: 506,
        image: "/images/mutton-awadhi-biryani.png",
        description: "Royal Awadhi biryani.",
        type: "nonVeg",
      },
      {
        id: 4,
        dishName: "Spl. Mutton Biryani (2 Pcs + Egg)",
        price: 506,
        image: "/images/spl-mutton-biryani.png",
        description: "Loaded mutton biryani.",
        type: "nonVeg",
      },
      {
        id: 5,
        dishName: "Chicken Biryani",
        price: 200,
        image: "/images/chicken-biryani.png",
        description: "Authentic chicken biryani.",
        type: "nonVeg",
      },
      {
        id: 6,
        dishName: "Spl. Chicken Biryani (2 Pcs + Egg)",
        price: 295,
        image: "/images/spl-chicken-biryani.png",
        description: "Special chicken biryani.",
        type: "nonVeg",
      },
      {
        id: 7,
        dishName: "Biryani Rice",
        price: 137,
        image: "/images/biryani-rice.png",
        description: "Fragrant biryani rice.",
        type: "veg",
      },
      {
        id: 8,
        dishName: "Egg Biryani (2 Pcs)",
        price: 169,
        image: "/images/egg-biryani.png",
        description: "Flavorful egg biryani.",
        type: "nonVeg",
      },
      {
        id: 9,
        dishName: "1Kg Mutton Biryani",
        price: 411,
        image: "/images/1kg-mutton-biryani.png",
        description: "Family pack biryani.",
        type: "nonVeg",
      },
      {
        id: 10,
        dishName: "1Kg Chicken Biryani",
        price: 264,
        image: "/images/1kg-chicken-biryani.png",
        description: "Family chicken biryani.",
        type: "nonVeg",
      },
      {
        id: 11,
        dishName: "Extra Mutton",
        price: 211,
        image: "/images/extra-mutton.png",
        description: "Extra mutton pieces.",
        type: "nonVeg",
      },
      {
        id: 12,
        dishName: "Extra Chicken",
        price: 127,
        image: "/images/extra-chicken.png",
        description: "Extra chicken pieces.",
        type: "nonVeg",
      },
      {
        id: 13,
        dishName: "Extra Aloo",
        price: 11,
        image: "/images/extra-aloo.png",
        description: "Extra potato piece.",
        type: "veg",
      },
      {
        id: 14,
        dishName: "Extra Egg",
        price: 21,
        image: "/images/extra-egg.png",
        description: "Boiled egg add-on.",
        type: "nonVeg",
      },
      {
        id: 15,
        dishName: "Steam Rice",
        price: 95,
        image: "/images/steam-rice.png",
        description: "Fresh steamed rice.",
        type: "veg",
      },
      {
        id: 16,
        dishName: "Jeera Rice",
        price: 148,
        image: "/images/jeera-rice.png",
        description: "Cumin flavored rice.",
        type: "veg",
      },
      {
        id: 17,
        dishName: "Peas Pulao",
        price: 148,
        image: "/images/peas-pulao.png",
        description: "Peas flavored pulao.",
        type: "veg",
      },
      {
        id: 18,
        dishName: "Mix Veg Pulao",
        price: 169,
        image: "/images/mix-veg-pulao.png",
        description: "Mixed vegetable pulao.",
        type: "veg",
      },
    ],

    Chinese: [
      {
        id: 1,
        dishName: "Chicken 65 (8 Pcs)",
        price: 274,
        image: "/images/chicken-65.png",
        description: "Spicy crispy chicken bites.",
        type: "nonVeg",
      },
      {
        id: 2,
        dishName: "Chicken Chilli (8 Pcs)",
        price: 475,
        image: "/images/chicken-chilli.png",
        description: "Spicy chicken in sauce.",
        type: "nonVeg",
      },
      {
        id: 3,
        dishName: "Chicken Manchurian (8 Pcs)",
        price: 327,
        image: "/images/chicken-manchurian.png",
        description: "Chicken in Manchurian gravy.",
        type: "nonVeg",
      },
      {
        id: 4,
        dishName: "Chicken Chilli Dry (8 Pcs)",
        price: 327,
        image: "/images/chicken-chilli-dry.png",
        description: "Dry spicy chicken.",
        type: "nonVeg",
      },
      {
        id: 5,
        dishName: "Fish 65 (6 Pcs)",
        price: 475,
        image: "/images/fish-65.png",
        description: "Crispy spicy fish.",
        type: "nonVeg",
      },
      {
        id: 6,
        dishName: "Crispy Chilli Baby Corn",
        price: 264,
        image: "/images/chilli-baby-corn.png",
        description: "Crispy baby corn.",
        type: "veg",
      },
      {
        id: 7,
        dishName: "Paneer Manchurian",
        price: 306,
        image: "/images/paneer-manchurian.png",
        description: "Paneer in Manchurian sauce.",
        type: "veg",
      },
      {
        id: 8,
        dishName: "Chilli Prawn",
        price: 315,
        image: "/images/chilli-prawn.png",
        description: "Spicy chilli prawns.",
        type: "nonVeg",
      },
      {
        id: 9,
        dishName: "Drum Stick",
        price: 306,
        image: "/images/drum-stick.png",
        description: "Crispy chicken drumsticks.",
        type: "nonVeg",
      },
      {
        id: 10,
        dishName: "Chicken Chowmein",
        price: 232,
        image: "/images/chicken-chowmein.png",
        description: "Chicken stir-fried noodles.",
        type: "nonVeg",
      },
      {
        id: 11,
        dishName: "Mixed Chowmein",
        price: 306,
        image: "/images/mixed-chowmein.png",
        description: "Mixed meat noodles.",
        type: "nonVeg",
      },
      {
        id: 12,
        dishName: "Chicken Hakka Noodles",
        price: 369,
        image: "/images/chicken-hakka-noodles.png",
        description: "Hakka style noodles.",
        type: "nonVeg",
      },
      {
        id: 13,
        dishName: "Chicken Fried Rice",
        price: 285,
        image: "/images/chicken-fried-rice.png",
        description: "Classic fried rice.",
        type: "nonVeg",
      },
      {
        id: 14,
        dishName: "Mixed Fried Rice",
        price: 243,
        image: "/images/mixed-fried-rice.png",
        description: "Mixed meat fried rice.",
        type: "nonVeg",
      },
      {
        id: 15,
        dishName: "Egg Fried Rice",
        price: 232,
        image: "/images/egg-fried-rice.png",
        description: "Egg tossed fried rice.",
        type: "nonVeg",
      },
      {
        id: 16,
        dishName: "Veg Fried Rice",
        price: 243,
        image: "/images/veg-fried-rice.png",
        description: "Vegetable fried rice.",
        type: "veg",
      },
      {
        id: 17,
        dishName: "Chicken Lollipop",
        price: 306,
        image: "/images/chicken-lollipop.png",
        description: "Juicy chicken lollipop.",
        type: "nonVeg",
      },
      {
        id: 18,
        dishName: "Crispy Chicken",
        price: 295,
        image: "/images/crispy-chicken.png",
        description: "Golden fried chicken.",
        type: "nonVeg",
      },
      {
        id: 19,
        dishName: "Chicken Momo",
        price: 211,
        image: "/images/chicken-momo.png",
        description: "Steamed chicken momos.",
        type: "nonVeg",
      },
      {
        id: 20,
        dishName: "Pan Fry Fish",
        price: 317,
        image: "/images/pan-fry-fish.png",
        description: "Pan-fried fresh fish.",
        type: "nonVeg",
      },
      {
        id: 21,
        dishName: "Chicken Clear Soup",
        price: 137,
        image: "/images/chicken-clear-soup.png",
        description: "Light chicken soup.",
        type: "nonVeg",
      },
      {
        id: 22,
        dishName: "Chicken Pepper Fry",
        price: 290,
        image: "/images/chicken-pepper-fry.png",
        description: "Pepper spicy chicken.",
        type: "nonVeg",
      },
      {
        id: 23,
        dishName: "Prawn Pepper Salt",
        price: 506,
        image: "/images/prawn-pepper-salt.png",
        description: "Pepper salt prawns.",
        type: "nonVeg",
      },
      {
        id: 24,
        dishName: "Chicken Sweet Corn Soup",
        price: 158,
        image: "/images/chicken-sweet-corn-soup.png",
        description: "Sweet corn chicken soup.",
        type: "nonVeg",
      },
    ],

    ChickeninGravy: [
      {
        id: 1,
        dishName: "Dawat-e-Hind Spl. Chicken (4 Pcs)",
        price: 290,
        image: "/images/dawat-special-chicken.png",
        description: "House special chicken curry.",
        type: "nonVeg",
      },
      {
        id: 2,
        dishName: "Chicken Chaap (1 Pc)",
        price: 206,
        image: "/images/chicken-chaap.png",
        description: "Rich spicy chicken chaap.",
        type: "nonVeg",
      },
      {
        id: 3,
        dishName: "Chicken Rezala (1 Pc)",
        price: 216,
        image: "/images/chicken-rezala.png",
        description: "Creamy Mughlai chicken.",
        type: "nonVeg",
      },
      {
        id: 4,
        dishName: "Chicken Quorma (2 Pcs)",
        price: 216,
        image: "/images/chicken-quorma.png",
        description: "Classic chicken quorma.",
        type: "nonVeg",
      },
      {
        id: 5,
        dishName: "Chicken Tandoori Butter Masala (4 Pcs)",
        price: 364,
        image: "/images/chicken-tandoori-butter-masala.png",
        description: "Tandoori chicken in butter gravy.",
        type: "nonVeg",
      },
      {
        id: 6,
        dishName: "Chicken Tandoori Butter Masala (2 Pcs)",
        price: 248,
        image: "/images/chicken-tandoori-butter-masala-half.png",
        description: "Half butter masala.",
        type: "nonVeg",
      },
      {
        id: 7,
        dishName: "Tangri Butter Masala (2 Pcs)",
        price: 290,
        image: "/images/tangri-butter-masala.png",
        description: "Tangri in butter gravy.",
        type: "nonVeg",
      },
      {
        id: 8,
        dishName: "Chicken Tikka Butter Masala (4 Pcs)",
        price: 269,
        image: "/images/chicken-tikka-butter-masala.png",
        description: "Chicken tikka butter masala.",
        type: "nonVeg",
      },
      {
        id: 9,
        dishName: "Chicken Reshmi Butter Masala (4 Pcs)",
        price: 290,
        image: "/images/chicken-reshmi-butter-masala.png",
        description: "Creamy reshmi chicken.",
        type: "nonVeg",
      },
      {
        id: 10,
        dishName: "Chicken Hariyali Butter Masala (4 Pcs)",
        price: 269,
        image: "/images/chicken-hariyali-butter-masala.png",
        description: "Hariyali butter chicken.",
        type: "nonVeg",
      },
      {
        id: 11,
        dishName: "Chicken Kassa (2 Pcs)",
        price: 227,
        image: "/images/chicken-kassa.png",
        description: "Spicy Bengali chicken.",
        type: "nonVeg",
      },
      {
        id: 12,
        dishName: "Chicken Masala (2 Pcs)",
        price: 227,
        image: "/images/chicken-masala.png",
        description: "Classic masala chicken.",
        type: "nonVeg",
      },
      {
        id: 13,
        dishName: "Chicken Lahori (6 Pcs)",
        price: 258,
        image: "/images/chicken-lahori.png",
        description: "Authentic Lahori chicken.",
        type: "nonVeg",
      },
      {
        id: 14,
        dishName: "Palak Chicken",
        price: 216,
        image: "/images/palak-chicken.png",
        description: "Chicken cooked with spinach.",
        type: "nonVeg",
      },
      {
        id: 15,
        dishName: "Chicken Lababdar (6 Pcs)",
        price: 269,
        image: "/images/chicken-lababdar.png",
        description: "Rich creamy chicken.",
        type: "nonVeg",
      },
      {
        id: 16,
        dishName: "Chicken Kadai (2 Pcs)",
        price: 227,
        image: "/images/chicken-kadai.png",
        description: "Spicy kadai chicken.",
        type: "nonVeg",
      },
      {
        id: 17,
        dishName: "Chicken Handi (4 Pcs)",
        price: 385,
        image: "/images/chicken-handi.png",
        description: "Traditional handi chicken.",
        type: "nonVeg",
      },
      {
        id: 18,
        dishName: "Chicken Do-Piyaza (4 Pcs)",
        price: 364,
        image: "/images/chicken-do-piyaza.png",
        description: "Chicken with onions.",
        type: "nonVeg",
      },
      {
        id: 19,
        dishName: "Tawa Chicken Boneless (6 Pcs)",
        price: 295,
        image: "/images/tawa-chicken-boneless.png",
        description: "Boneless tawa chicken.",
        type: "nonVeg",
      },
      {
        id: 20,
        dishName: "Dum Chicken with Bone (4 Pcs)",
        price: 243,
        image: "/images/dum-chicken.png",
        description: "Slow-cooked chicken.",
        type: "nonVeg",
      },
      {
        id: 21,
        dishName: "Chicken Rara (2 Pcs)",
        price: 269,
        image: "/images/chicken-rara.png",
        description: "Rich rara chicken.",
        type: "nonVeg",
      },
      {
        id: 22,
        dishName: "Chicken Bharta (Shredded)",
        price: 258,
        image: "/images/chicken-bharta.png",
        description: "Shredded chicken curry.",
        type: "nonVeg",
      },
      {
        id: 23,
        dishName: "Chicken Peshawari (Shredded)",
        price: 258,
        image: "/images/chicken-peshawari.png",
        description: "Peshawari style chicken.",
        type: "nonVeg",
      },
      {
        id: 24,
        dishName: "Methi Chicken (2 Pcs)",
        price: 269,
        image: "/images/methi-chicken.png",
        description: "Fenugreek chicken curry.",
        type: "nonVeg",
      },
      {
        id: 25,
        dishName: "Chicken Keema Masala",
        price: 248,
        image: "/images/chicken-keema-masala.png",
        description: "Minced chicken masala.",
        type: "nonVeg",
      },
      {
        id: 26,
        dishName: "Chicken Chana Masala",
        price: 185,
        image: "/images/chicken-chana-masala.png",
        description: "Chicken with chickpeas.",
        type: "nonVeg",
      },
      {
        id: 27,
        dishName: "Chicken Tarka",
        price: 174,
        image: "/images/chicken-tarka.png",
        description: "Spicy chicken tarka.",
        type: "nonVeg",
      },
      {
        id: 28,
        dishName: "Egg Chicken Tarka",
        price: 195,
        image: "/images/egg-chicken-tarka.png",
        description: "Egg chicken tarka.",
        type: "nonVeg",
      },
      {
        id: 29,
        dishName: "Afghani Butter Masala (Full)",
        price: 359,
        image: "/images/afghani-butter-masala-full.png",
        description: "Full Afghani butter chicken.",
        type: "nonVeg",
      },
      {
        id: 30,
        dishName: "Afghani Butter Masala (Half)",
        price: 259,
        image: "/images/afghani-butter-masala-half.png",
        description: "Half Afghani butter chicken.",
        type: "nonVeg",
      },
    ],

    Dessert: [
      {
        id: 1,
        dishName: "Firni",
        price: 69,
        image: "/images/firni.png",
        description: "Creamy traditional rice dessert.",
        type: "veg",
      },
      {
        id: 2,
        dishName: "Shahi Tukda",
        price: 121,
        image: "/images/shahi-tukda.png",
        description: "Royal bread sweet.",
        type: "veg",
      },
      {
        id: 3,
        dishName: "Shahi Kheer",
        price: 60,
        image: "/images/shahi-kheer.png",
        description: "Rich creamy rice pudding.",
        type: "veg",
      },
      {
        id: 4,
        dishName: "Gajar Halwa",
        price: 132,
        image: "/images/gajar-halwa.png",
        description: "Classic carrot dessert.",
        type: "veg",
      },
      {
        id: 5,
        dishName: "Masala Cold Drinks",
        price: 58,
        image: "/images/masala-cold-drink.png",
        description: "Refreshing masala drink.",
        type: "veg",
      },
      {
        id: 6,
        dishName: "Gulab Jamun (2 Pcs)",
        price: 58,
        image: "/images/gulab-jamun.png",
        description: "Soft syrupy gulab jamun.",
        type: "veg",
      },
      {
        id: 7,
        dishName: "Gulab Jamun With Ice Cream",
        price: 157,
        image: "/images/gulab-jamun-ice-cream.png",
        description: "Gulab jamun with ice cream.",
        type: "veg",
      },
      {
        id: 8,
        dishName: "Ice Cream (2 Scoop Any Flavour)",
        price: 90,
        image: "/images/ice-cream.png",
        description: "Two scoops of ice cream.",
        type: "veg",
      },
    ],

    Beverages: [
      {
        id: 1,
        dishName: "Package Water (1/2 Ltr.)",
        price: 10,
        image: "/images/package-water-half.png",
        description: "500ml mineral water.",
        type: "veg",
      },
      {
        id: 2,
        dishName: "Package Water (1 Ltr.)",
        price: 20,
        image: "/images/package-water-1l.png",
        description: "1 litre mineral water.",
        type: "veg",
      },
      {
        id: 3,
        dishName: "Container Small",
        price: 5,
        image: "/images/container-small.png",
        description: "Small takeaway container.",
        type: "veg",
      },
      {
        id: 4,
        dishName: "Container",
        price: 11,
        image: "/images/container.png",
        description: "Regular takeaway container.",
        type: "veg",
      },
      {
        id: 5,
        dishName: "Cold Drink (200ml)",
        price: 11,
        image: "/images/cold-drink-small.png",
        description: "Chilled soft drink.",
        type: "veg",
      },
      {
        id: 6,
        dishName: "Cold Drink (300ml)",
        price: 21,
        image: "/images/cold-drink-medium.png",
        description: "Refreshing soft drink.",
        type: "veg",
      },
      {
        id: 7,
        dishName: "Cold Drink (500ml)",
        price: 32,
        image: "/images/cold-drink-large.png",
        description: "Large chilled beverage.",
        type: "veg",
      },
      {
        id: 8,
        dishName: "Cold Drink (1L)",
        price: 58,
        image: "/images/cold-drink-1l.png",
        description: "Family size cold drink.",
        type: "veg",
      },
    ],

    MuttoninGravy: [
      {
        id: 1,
        dishName: "Mutton Chaap",
        price: 317,
        image: "/images/mutton-chaap.png",
        description: "Rich spicy mutton chaap.",
        type: "nonVeg",
      },
      {
        id: 2,
        dishName: "Mutton Kali Mirch (4 Pcs)",
        price: 529,
        image: "/images/mutton-kali-mirch.png",
        description: "Pepper flavored mutton.",
        type: "nonVeg",
      },
      {
        id: 3,
        dishName: "Mutton Stew (2 Pcs)",
        price: 295,
        image: "/images/mutton-stew.png",
        description: "Slow-cooked mutton stew.",
        type: "nonVeg",
      },
      {
        id: 4,
        dishName: "Mutton Rezala (1 Pc)",
        price: 317,
        image: "/images/mutton-rezala.png",
        description: "Creamy Mughlai mutton.",
        type: "nonVeg",
      },
      {
        id: 5,
        dishName: "Mutton Pasinda",
        price: 348,
        image: "/images/mutton-pasinda.png",
        description: "Tender royal mutton.",
        type: "nonVeg",
      },
      {
        id: 6,
        dishName: "Mutton Quorma (2 Pcs)",
        price: 317,
        image: "/images/mutton-quorma.png",
        description: "Classic mutton quorma.",
        type: "nonVeg",
      },
      {
        id: 7,
        dishName: "Mutton Kassa (2 Pcs)",
        price: 295,
        image: "/images/mutton-kassa.png",
        description: "Spicy Bengali mutton.",
        type: "nonVeg",
      },
      {
        id: 8,
        dishName: "Mutton Masala (2 Pcs)",
        price: 306,
        image: "/images/mutton-masala.png",
        description: "Traditional mutton curry.",
        type: "nonVeg",
      },
      {
        id: 9,
        dishName: "Mutton Handi (4 Pcs)",
        price: 528,
        image: "/images/mutton-handi.png",
        description: "Handi cooked mutton.",
        type: "nonVeg",
      },
      {
        id: 10,
        dishName: "Mutton Kadai (2 Pcs)",
        price: 306,
        image: "/images/mutton-kadai.png",
        description: "Spicy kadai mutton.",
        type: "nonVeg",
      },
      {
        id: 11,
        dishName: "Mutton Do-Piyaza (4 Pcs)",
        price: 528,
        image: "/images/mutton-do-piyaza.png",
        description: "Mutton with onions.",
        type: "nonVeg",
      },
      {
        id: 12,
        dishName: "Mutton Rara (2 Pcs)",
        price: 401,
        image: "/images/mutton-rara.png",
        description: "Rich rara mutton.",
        type: "nonVeg",
      },
      {
        id: 13,
        dishName: "Mutton Keema Masala",
        price: 306,
        image: "/images/mutton-keema-masala.png",
        description: "Minced mutton masala.",
        type: "nonVeg",
      },
      {
        id: 14,
        dishName: "Mutton Tikia",
        price: 179,
        image: "/images/mutton-tikia.png",
        description: "Crispy mutton tikia.",
        type: "nonVeg",
      },
      {
        id: 15,
        dishName: "Mutton Tarka",
        price: 222,
        image: "/images/mutton-tarka.png",
        description: "Spicy mutton tarka.",
        type: "nonVeg",
      },
      {
        id: 16,
        dishName: "Mutton Egg Tarka",
        price: 232,
        image: "/images/mutton-egg-tarka.png",
        description: "Egg mutton tarka.",
        type: "nonVeg",
      },
      {
        id: 17,
        dishName: "Mutton Keema Chana",
        price: 243,
        image: "/images/mutton-keema-chana.png",
        description: "Keema with chickpeas.",
        type: "nonVeg",
      },
      {
        id: 18,
        dishName: "Mutton Liver Kassa",
        price: 295,
        image: "/images/mutton-liver-kassa.png",
        description: "Spicy liver curry.",
        type: "nonVeg",
      },
      {
        id: 19,
        dishName: "Mutton Paya (1 Pc)",
        price: 158,
        image: "/images/mutton-paya.png",
        description: "Traditional paya curry.",
        type: "nonVeg",
      },
      {
        id: 20,
        dishName: "Mutton Kofta (4 Pcs)",
        price: 379,
        image: "/images/mutton-kofta.png",
        description: "Juicy mutton kofta.",
        type: "nonVeg",
      },
    ],

    Salad: [
      {
        id: 1,
        dishName: "Green Salad",
        price: 53,
        image: "/images/green-salad.png",
        description: "Fresh mixed vegetable salad.",
        type: "veg",
      },
      {
        id: 2,
        dishName: "Onion Salad",
        price: 32,
        image: "/images/onion-salad.png",
        description: "Fresh sliced onions.",
        type: "veg",
      },
      {
        id: 3,
        dishName: "Ghol",
        price: 32,
        image: "/images/ghol.png",
        description: "Refreshing salted buttermilk.",
        type: "veg",
      },
      {
        id: 4,
        dishName: "Mix Veg. Raita",
        price: 39,
        image: "/images/mix-veg-raita.png",
        description: "Curd with fresh vegetables.",
        type: "veg",
      },
    ],

    FishinGravy: [
      {
        id: 1,
        dishName: "Fish Tikka Butter Masala (2 Pcs)",
        price: 327,
        image: "/images/fish-tikka-butter-masala-half.png",
        description: "Creamy fish butter masala.",
        type: "nonVeg",
      },
      {
        id: 2,
        dishName: "Fish Tikka Butter Masala (4 Pcs)",
        price: 472,
        image: "/images/fish-tikka-butter-masala-full.png",
        description: "Rich fish butter masala.",
        type: "nonVeg",
      },
      {
        id: 3,
        dishName: "Fish Masala (2 Pcs)",
        price: 306,
        image: "/images/fish-masala-half.png",
        description: "Spicy fish curry.",
        type: "nonVeg",
      },
      {
        id: 4,
        dishName: "Fish Masala (4 Pcs)",
        price: 324,
        image: "/images/fish-masala-full.png",
        description: "Classic fish masala.",
        type: "nonVeg",
      },
      {
        id: 5,
        dishName: "Kadai Fish (2 Pcs)",
        price: 306,
        image: "/images/kadai-fish-half.png",
        description: "Spicy kadai fish.",
        type: "nonVeg",
      },
      {
        id: 6,
        dishName: "Kadai Fish (4 Pcs)",
        price: 324,
        image: "/images/kadai-fish-full.png",
        description: "Authentic kadai fish.",
        type: "nonVeg",
      },
      {
        id: 7,
        dishName: "Prawn Do-Piyaza (4 Pcs)",
        price: 358,
        image: "/images/prawn-do-piyaza.png",
        description: "Prawns with onions.",
        type: "nonVeg",
      },
      {
        id: 8,
        dishName: "Prawn Masala (4 Pcs)",
        price: 358,
        image: "/images/prawn-masala.png",
        description: "Spicy prawn masala.",
        type: "nonVeg",
      },
      {
        id: 9,
        dishName: "Prawn Tikka Masala (4 Pcs)",
        price: 377,
        image: "/images/prawn-tikka-masala.png",
        description: "Creamy prawn tikka curry.",
        type: "nonVeg",
      },
    ],
  };

  const dishes = allDishes[category.split(" ").join("")] || [];

  return (
    <div
      style={{ fontFamily: "Manrope, sans-serif" }}
      className="px-4 sm:px-6 md:px-10 lg:px-19 py-6"
    >
      {/* Category Name */}
      <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-5xl font-semibold">
        {category}
      </h1>

      {/* Description */}
      <h1
        style={{ fontFamily: "Poppins, sans-serif" }}
        className="mt-2 text-sm sm:text-base md:text-lg text-gray-600 max-w-4xl"
      >
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos,
        consequatur.
      </h1>

      {/* Heading */}
      <div className="flex items-center gap-2 mt-8 px-1 sm:px-2">
        <h1 className="font-black text-lg sm:text-xl md:text-2xl">
          Our All Best Category
        </h1>
        <ArrowRight className="w-5 h-5 sm:w-6 sm:h-6" strokeWidth={3.5} />
      </div>

      {/* Cards */}
      <div className="mt-6 grid grid-cols-2 px-1 sm:px-12 md:px-12 lg:px-12 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
        {dishes.map((elem) => (
          <CotegoryCard
            key={elem.id}
            id={elem.id}
            dishName={elem.dishName}
            price={elem.price}
            type={elem.type}
            description={elem.description}
          />
        ))}
      </div>
    </div>
  );
};

export default Kabab;
